version: "3.9"

services:
  python-app:
    build:
      dockerfile: Dockerfile
    container_name: python-app-container
    command: sh bootstrap.sh
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    environment:
      DATABASE_HOST: postgres-db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 0000

  postgres-db:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_PASSWORD: 0000
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
